### ISSUE TITLE
Drag and Drop over Player when playing

### ISSUE THREAD

**Issue by kvirusp** [jaruba/PowderPlayer#1]
When in Video mode, it should be possible to drag and drop a file over the video to add it to the playlist.

**Comment by kvirusp** [comment]
no access to playlist once i play a local video (shortcut works ctrl +L but no button displayed)
allso drag and drop to playlist does not work

**Comment by jaruba** [comment]
"Add Video" button added to playlist menu: https://github.com/jaruba/PowderPlayer/commit/051058f1d721ab8328052e05232434b8fedacac1

Drag and drop over player is still not possible atm.

**Comment by jaruba** [comment]
done, will be available in the next version
