### ISSUE TITLE
Possible bug on GUI

### ISSUE THREAD

**Issue by samukets** [jaruba/PowderPlayer#101]
Hello, when i reproduce mp3 and these mp3 has image on background and i open powder menu like to select other music from playlist GUI bugs on screen:

![image](https://cloud.githubusercontent.com/assets/2901904/13901104/20dc1c92-edf7-11e5-992d-eb08fbe7570a.png)

**Comment by jaruba** [comment]
I know what this is..

**Comment by samukets** [comment]
Another bug, when i drag and drop a folder with music powder dont identify all tracks... link to folder example:

https://drive.google.com/file/d/0B-zID4I33vBSQ0I1Wkt6NkNKMHM/view?usp=sharing

**Comment by jaruba** [comment]
As the entire tech used in Powder has been changed and the player re-written from scratch, this issue has now become invalid as it is related to old code that is no longer used.
