### ISSUE TITLE
error: this.refs.dialog.open

### ISSUE THREAD

**Issue by MaximilianLloyd** [jaruba/PowderPlayer#102]
Does anyone have any idea why this is happening? thanks :-)
![skjermbilde](https://cloud.githubusercontent.com/assets/10583205/14035771/42e75cfe-f232-11e5-9f2e-b0323b438d86.PNG)

**Comment by jaruba** [comment]
I have a good idea of why your getting those errors. The `react-polymer` branch (nightly) is still highly unstable, I just switched to `polymer` over `material-ui` 2 days ago.

I'm gonna push the entire torrent dashboard component and logic today (hopefully) and that should also fix the `polymer` not loading issue that your having. :)

I'll give you a shout to test again when it's done.

**Comment by MaximilianLloyd** [comment]
ok cool :-)

**Comment by jaruba** [comment]
Give it a try now

**Comment by jaruba** [comment]
Ok, I think I fixed all the building issues with the last commits. If you find any more issues, please reopen this ticket. :)
