### ISSUE TITLE
Audio's Fine..... No Video

### ISSUE THREAD

**Issue by avmduck** [jaruba/PowderPlayer#105]
Audio is working video is not!
    I know.... Its probably a missing codec or something simple like that

Someone PLZ help
   Maybe give me a link to a Codec's Pack they are using    TY
Windows 7 Pro 32bit
PowderPlayer 0.98
VLC 2.1.2

**Comment by jaruba** [comment]
How are you using Powder? Are you streaming to VLC or to the Internal Player?

**Comment by avmduck** [comment]
Internal Player

**Comment by jaruba** [comment]
Could you download and run DebugView: https://technet.microsoft.com/en-us/sysinternals/debugview.aspx

And with it open, try to play something in Powder again? Then screenshot the DebugView window and post it here?

**Comment by avmduck** [comment]
Just switched it over to VLC 
Working fine in VLC

Yes Sir.... I will give that a try(download and run)
TY 4 your quick tech support!

**Comment by avmduck** [comment]
with  VLC running

[3680] core libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
[3680] core playlist: stopping playback
[3680] core input error: ES_OUT_SET_(GROUP_)PCR  is called too late (pts_delay increased to 1000 ms)
[3680] core input error: ES_OUT_RESET_PCR called
[3680] mpgatofixed32 audio converter error: libmad error: bad main_data_begin pointer
[3680] mpgatofixed32 audio converter error: libmad error: bad main_data_begin pointer

without VLC nothing but Prebuffering

**Comment by jaruba** [comment]
uhm, that's strange, using the internal player, could you press `CTRL` + `D` then make sure the `console` tab is active, and see if there is any error there when it stops in the prebuffering stage?

**Comment by avmduck** [comment]
Unable to initialize WebGL,  C:\Program Files\Powder Player\node_modules\wcjs-renderer\index.js:54  falling back to canvas rendering
TypeError     C:\Program Files\Powder Player\node_modules\torrent-worker\index.js:57

**Comment by jaruba** [comment]
Do you have DirectX installed? If so, which version?

**Comment by avmduck** [comment]
DirectX 11

**Comment by jaruba** [comment]
Could you try opening the `package.json` file from Powder Player's install directory (with any text editor) and removing just `--d3d9 --disable-d3d11 ` from this line:
```
    "chromium-args": "--d3d9 --disable-d3d11 --gpu-no-context-lost --ignore-gpu-blacklist",
```

**Comment by jaruba** [comment]
Then ofcourse, test again. :)

**Comment by avmduck** [comment]
[4036] core vout display error: Failed to change zoom
[4036] core vout display error: Failed to set on top
[4036] core vout display error: Failed to change source AR

Same problem... audio fine... no video......   long time to load

**Comment by jaruba** [comment]
```
[4036] core vout display error: Failed to change zoom
[4036] core vout display error: Failed to set on top
[4036] core vout display error: Failed to change source AR
```

These are OK, it means that libVLC started correctly in our case. I'm guessing you still have the same errors in the Console though?

**Comment by avmduck** [comment]
No Console
No Settings........
Program frozen..... when it does disappear (using Task Manager) from display and taskbar
Audio continues playing
lmao at this one! (sorry  about the headache)(i'll just use it with VLC) 

If something changes.... i'll post it here
Thank  You for the help :)

**Comment by avmduck** [comment]
Or if you would like me to try something else
post it here and I will

Going to return my package.json file to normal
then I have to run

thanx again

**Comment by jaruba** [comment]
I'll think about it more.. I can't imagine why you would have issues with WebGL atm. If I figure something out I'll give a shout.

**Comment by avmduck** [comment]
Any ideas, jaruba?
I have tried everything I can think of....

OS Reload
Deleting and Reallowing Firewall
Shutting down Firewall
Hardwire my internet connection instead of wifi
Reinstall Powder 5 or 6 times 
Reinstall Powder back as far as 0.95
Checked Media Sharing
            The only thing that gives me hope is:  doing ~Sequence~
Left Click (on Powder)/Torrent/Torrent Data
Left Click (on Powder) / Up Arrow Key (to bring back Main Viewer /File name finally appears Top Right of Player)
       now if I do the ~Sequence~ agian It will start downloading then the Sound will start but no video(after sound starts program Freezes up)

Now if I hit Settings / Stream to TV (DLNA)/ before sound starts it will play fine on my Big Screen TV
Please don't ask How I found this out.... lmfao
yes i've been at it for awhile
    Any input would b appreciated
Debug says:
1      0.00000000      [1236]   http access error: failed to read answer
2      0.00054072      [1236]   http access error: seek failed
       after  ~Sequence~  ~Sequence~ Settings / Stream to TV (DLNA)

**Comment by jaruba** [comment]
Lool, you definitely tried quite a few things. From the error your getting, it's some sort of issue related to your graphic's driver, your best bet is trying to install the latest graphic card driver and reinstalling DirectX, if it still doesn't work, then try to remove this entire line from `package.json`:

```
    "chromium-args": "--d3d9 --disable-d3d11 --gpu-no-context-lost --ignore-gpu-blacklist",
```
(the same line we modified before)

**Comment by jaruba** [comment]
Is this still an issue? If so, can you try it with Powder Player Nightly too?

**Comment by jaruba** [comment]
This issue is old, closing
