### ISSUE TITLE
Can you occasionally compile a beta build?

### ISSUE THREAD

**Issue by 49c29fa9** [jaruba/PowderPlayer#106]
Or even an alpha or nightly. Thanks

**Comment by jaruba** [comment]
I always intended to build it for testing, but I just don't think it's in a usable state yet, there are still some things that need to be done before it becomes coherent enough for a build.

**Comment by avmduck** [comment]
)-:

**Comment by MakeshVineeth** [comment]
Eagerly waiting for the alpha build...

**Comment by jaruba** [comment]
A pre-release of Powder Player Nightly (v1.00) is now available for download for all platforms.

Please read the announcement carefully and get the download link from this page:
https://www.reddit.com/r/PowderPlayer/comments/4ralk2/powder_player_v100_prerelease_available_for/
