### ISSUE TITLE
OSX or Ubuntu Support

### ISSUE THREAD

**Issue by HDVinnie** [jaruba/PowderPlayer#109]
Will this ever wok on OSX or Ubuntu ?

**Comment by jaruba** [comment]
what do you mean? there is already a Linux and OSX version: http://powder.media/download

**Comment by HDVinnie** [comment]
my bad I assumed to fast reading README

Building Instructions:

For Windows only

**Comment by jaruba** [comment]
Keep in mind that the `react-polymer` branch that is the main branch now, is for the Nightly version, for which we didn't even release an Alpha publicly yet.

And no, this branch is highly unstable and wasn't tested cross-platform yet.

**Comment by jaruba** [comment]
Also, the `For Windows only` in the `README.md` is about that one line, that needs to be written only in Windows to ensure it will build for 32bit.
