### ISSUE TITLE
[Feature] Override macOS energy saver

### ISSUE THREAD

**Issue by phixofor** [jaruba/PowderPlayer#115]
[Nightly]

The display goes dim and ultimately off during video playback.

Not a problem when casting, so maybe a simple on/off setting for it will suffice?

**Comment by jaruba** [comment]
I just received an iMac from work so this will be easily testable / fixed.

Thanks for reporting this issue! :)

**Comment by jaruba** [comment]
Done, I fixed and tested it, it will be available in the next build of the nightly.
