### ISSUE TITLE
[Nightly] chrome cast failure after changing settings

### ISSUE THREAD

**Issue by roeycohen** [jaruba/PowderPlayer#122]
Hi,

When switching subtitles language while casting, the player fails to restart playing.
To solve the problem, i need to connect manually to the device (using google's app) and stop it.
then pressing the cast button again works.

please let me know if you need more details...

Roey

**Comment by jaruba** [comment]
Interesting, I'll test it out tomorrow when I get home. :)

**Comment by jaruba** [comment]
I think this might be the same as #113 , could you do `CTRL` + `D` after it happens to see if the same error from that issue shows in the console log, please?

**Comment by roeycohen** [comment]
ok, i'll do it

**Comment by roeycohen** [comment]
Hi, 
i just checked and didn't get any errors in the console.
using chrome cast is virtually not possible, it's not possible to skip, change srt in the middle or make other changes...

**Comment by roeycohen** [comment]
it think it's now possible to emulate chrome using this:
https://www.google.com/edu/cast-for-edu/

**Comment by jaruba** [comment]
I believe this was fixed, I found another issue with chromecast connections though that could of been related to this issue also and will be available in the next release.
