### ISSUE TITLE
Powder (Nightley) = White square when open app (no problems before)

### ISSUE THREAD

**Issue by Draxler** [jaruba/PowderPlayer#127]
Win7/64b

When i try to open POwder Nightley it opens white square (app sized). I never had any problems before but now i try to reinstal nothing changed1 Is there maybe anything i need to install onto my PC beside Powder Nightley ? 
Any help would be much appreciated.

THis is how it looks when open player:

![screenshot_2](https://cloud.githubusercontent.com/assets/7681671/25952825/fd18c3fa-3661-11e7-858d-1d0f61a0042a.png)

**Comment by jaruba** [comment]
I've received a similar issue report from a friend, I personally have no such problems, it works ok for me. I'll go to his place one of these days to check out the issue and find a fix. There should be nothing else that needs installing except the Player itself.
Thank you for your report.

**Comment by Draxler** [comment]
i tryed ''everything'', instaling reinstaling various programs, reinstaling Powder, nothing worked.. At the same time my Kodi got upgrades when Nightley stop working and same when Powder Nightley start working again. Coincedence,, i don't know..
I hope you could find what was/is the issue ..

**Comment by jaruba** [comment]
I truly have no idea why it happens, it never did for me and i have the same version as you and my friend installed.. I need to be on a PC where it happens to understand what's wrong.

**Comment by jaruba** [comment]
but i can tell you it has nothing to do with kodi, that's for sure :)

**Comment by Draxler** [comment]
ok, :)  just sayng what i observed .. Real couse for this ''blackout'' is mystery for now,  it seams :)

**Comment by jaruba** [comment]
I think this is because i forgot to pay the domain name and it was down for a week, must of caused an error in the player's attempt to check for a new version..

If this happens again, please don't hesitate to tell me.. until then i'll consider it fixed.

**Comment by Draxler** [comment]
Would player it self be fixed of this bug in near future? (it's big bug if unreachable domain could kill this player of completley when check for update) I really like to use Nightley version for watching videos in general, so i'm litlle wory about that issue ..

**Comment by jaruba** [comment]
The domain + hosting are now payed for another year, so you clearly won't have this problem again any time soon, but I agree that the player should be completely decentralized and continue working even if the world ends tomorrow.

I'll reopen the issue until i actually commit a fix for it, you're right in thinking that this shouldn't be closed until it's actually fixed and can't be a problem ever again.

Thank you for being a Powder user and fan.

**Comment by ghost** [comment]
Got the same situation with white box and that is all. Version 1.10

**Comment by jaruba** [comment]
@Vasik76 what OS are you on?

**Comment by ghost** [comment]
@jaruba 
[user@user-pc ~]$ uname -a
Linux user-pc 4.9.40-1-MANJARO #1 SMP PREEMPT Fri Jul 28 09:24:52 UTC 2017 x86_64 GNU/Linux
[user@user-pc ~]$ cat /etc/*release*
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=17.0.2
DISTRIB_CODENAME=Gellivara
DISTRIB_DESCRIPTION="Manjaro Linux"
Is there any logs or something like?

**Comment by Draxler** [comment]
your both websites Domain are down and both Powder players are down since then. 
This is realy becoming an issue if player is depanded on website (domain) ..

**Comment by Draxler** [comment]
win7/64b
Update:
Websites are up but maybe domain app uses isn't? Still couldn't use Nigtley build or V.1.10 - 
still got white square issue when open Powder app. 
Yesterday i watched video on Powder = V.1.1.0 and when i close it and then reopen Powder app 1 min later i got this issue with white square again..

**Comment by Draxler** [comment]
Win7/64B

Since yesterday (everything worked fine before) i get white square (again) when try to open Powder player. This issue is present for both builds; Nightley & latest V.1.1.0 ..

**Comment by Draxler** [comment]
today  i reinstall both Nightley and v.1.1.0 version and nothing changed. Still got white square when open ether Powder version.

**Comment by jaruba** [comment]
Sorry, I was on vacation and forgot to pay the server again. Sorry for the inconvenience. :(

@Draxler I think you need to delete the settings folder of the apps so it can refresh accordingly, for Powder v1.1.0, if your on windows, the settings folder should be at `%AppData%\Powder-Player` (you can also try just renaming it instead of deleting, your choice)

**Comment by Draxler** [comment]
i'm on win7 OS
I couldn't find folder with name *Settings* in
%AppData%\local\Powder-Player 
or at 
%AppData%\Roaming\Powder-Player
______________________

Both app versions r still ''down''

**Comment by Draxler** [comment]
still down :  😢 

And i look again everywhere for folder named *Settings* in 
%AppData%\%local%\Powder-Player and in %AppData%\%Roaming%\Powder-Player
and there's no folder with that name in those Powder directorys.. (Win7/64B)
Regards

**Comment by Draxler** [comment]
UPDATE:

Today i uninstalled both POWDER app versions; V.1.0.0 (nightley) and V.1.1.0 (Stable) from my PC 
( WIN7 | 64/B). with *REVO unintaller* , app who's cappable deep uninistal-clenning from your PC leftovers that my stayed othervise behind with regular instalers. When i finsihed i also used CCleanner just to be sure all Powder leftovers gets cleaned from register and from other places as well.
Then i go into *temp* folder and clean that folder to empty this folder again (which CCleaner already done it) but few files were made it after and i cleaned these few files too just to be sure.
When i was sure there was no Powder files left in my PC i unistaled first stable POWDER app = V.0.9.8 
(which always worked regardless if domain was up or down if i remember corectley)
When app was installed it ask me if i want to keep this app 0.9.8 or i want to updated into new 1.1.0 app version. I chose to update directley from old v.0.9.8 onto new v.1.1.0 and when it was done with update all is working files since then again. Before i did all that i try to open bothe version Nigley and stable app and both app didn't worked and giving me the white square. Only afater i di9d allthat uninstaling and cleaning  and instakling with updating i mage to get all work again...

Regards

**Comment by jaruba** [comment]
This should be fixed with the release of v1.20
