### ISSUE TITLE
How to keep downloaded movies?

### ISSUE THREAD

**Issue by santiagobasulto** [jaruba/PowderPlayer#128]
Usually I can't watch an entire movie at once. It usually takes a few "sits". During the first sit, the entire movie is downloaded. But then the "movie" file is deleted. Is there any way to prevent that? To remove movies "older than 10 days" for example?

Thanks!

**Comment by jaruba** [comment]
In Powder Player v0.98 you can right click the video and select "Torrent > Close + Keep Files" to exit the player and keep the files. There is no setting that does this automatically.
In Powder Player v1.0 (Nightly) every time you close the player you get asked if you want to delete the files or not, there is also a checkbox with "Remember Choice".
There is no way to set something like "remove movies older than 10 days" in any of them.

**Comment by santiagobasulto** [comment]
Thank you very much @jaruba. Seems like I just have to update :)
