### ISSUE TITLE
Powder Nightley - Every 20 min.  goes to sleep

### ISSUE THREAD

**Issue by Draxler** [jaruba/PowderPlayer#130]
Win7/64b  |  Powder Nightley

When watching a movie (video), Powder Nightley goes to sleep (around) every 20 min. When this happens ''mouse'' needs to be moved to start Powder Nightley again and you need to repeat this every 20 min untill movie ends.

**Comment by jaruba** [comment]
You could disable sleep mode in your OS..

This has already been done, I just never made a new release since it was fixed because there are a few other things that need to be done before the official Powder Player v1.0 release.

I should be able to make an official release soon though.

**Comment by Draxler** [comment]
ok ,, i'll wait for Nightley release, since it's soon ..  :)

**Comment by jaruba** [comment]
This was solved some time ago
