### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by santiagobasulto** [jaruba/PowderPlayer#133]
Hello guys! Powder is streaming sound correctly, but video is completely black. I'm on Mac OS Sierra.

How can I debug this? Any logs written?

![image](https://user-images.githubusercontent.com/872296/31310720-9da26778-ab73-11e7-8bae-fe296d312794.png)

**Comment by jaruba** [comment]
thank you for your report, you can see the logs by using `CTRL` (`CMD`) + `D`

if there is any error in the log it would be of help to post it here, I'll look into this issue in an attempt to fix this for the next release

**Comment by kkan** [comment]
@jaruba Have same issue on High Sierra. Looks like happens only when streaming `.mkv` files.
<img width="1260" alt="screen shot 2018-01-06 at 05 48 59" src="https://user-images.githubusercontent.com/7046667/34635791-82d5b7aa-f2a5-11e7-9fed-0c30f91acac9.png">

**Comment by jaruba** [comment]
uhm, thank you for the error log.. it's hard to predict what's going on though, i suspect a vlc library failure. `.setPosition` is from the electron API though, but even that might be failing just because vlc doesn't render any image.. it would be very helpful to have a Mac with Sierra for testing.. I still use El Capitan

**Comment by jaruba** [comment]
@kkan one thing that could be really helpful is if you could send me either the torrent or file that you were trying to play when this error happened on my email (you can see it on [my profile](https://github.com/jaruba)), then I could try to reproduce it on El Capitan to see if it fails also

**Comment by kkan** [comment]
@jaruba Sent files on your email. I've just tested it on Windows 8 and Linux Mint. Works fine there.

**Comment by jaruba** [comment]
Thank you @kkan 
I had a chance to test the torrent files you sent. I only had issues with one of them not showing video though.

Can you try them again, and if the video doesn't play, can you try doing the following:
- Right Click on Video
- Select "Torrent" > "Torrent Data"
- On the new screen press the Gear Icon (top right of the window)
- Select "Go to Player"

And tell me if the video starts playing correctly after doing these steps?

**Comment by csi-kkan** [comment]
@jaruba
No, this didn't help. And I see the same error after going back to plater `Uncaught Error: Could not call remote function 'setPosition'.`

**Comment by pavsad** [comment]
Reporting the same problem.
MacOS 10.12.16
PowderPlayer - can't find an exact version. It's latest (download from http://powder.media/download)
Happens to any torrent file

**Comment by jaruba** [comment]
This is very strange, I have MacOS 10.13 High Sierra now, Powder works fine for me here.

@pavsad Can you send me the magnet link / torrent or video file that you tried on my email? (email is public on [my github profile](https://github.com/jaruba)). As I require a better testing scenario in order to reproduce this so I can fix it.

**Comment by jaruba** [comment]
Thanks everyone, with your help I've (finally) managed to reproduce this issue and fix it. It will be available in the next version.

**Comment by jaruba** [comment]
This was included in the latest release.

I'm pretty sure that this bug can't happen again with the change I made, but please make sure to test it when you can: https://github.com/jaruba/PowderPlayer/releases

**Comment by kkan** [comment]
@jaruba Yes, works fine for me now. Thank you!

**Comment by jaruba** [comment]
@kkan 
Glad to hear it! Just sad it took so long to identify / reproduce the bug.
I hope you'll enjoy the new version and won't have any more issues with it.
