### ISSUE TITLE
[Suggestion] Don't track history

### ISSUE THREAD

**Issue by Vastrix** [jaruba/PowderPlayer#136]
Hey,  
  
Like the program!
Would be cool if there were an option to shred any and all traces of watched videos.. :)

**Comment by jaruba** [comment]
Sure, making a No History setting wouldn't be hard, I'll try to add it until the next release.

**Comment by Vastrix** [comment]
Sweet, thanks :)

**Comment by jaruba** [comment]
don't close it or i might forget about it :)
