### ISSUE TITLE
[Bug] Playlist

### ISSUE THREAD

**Issue by Vastrix** [jaruba/PowderPlayer#139]
A few things I've noticed in 1.20

- Adding(/removing?) a file to the Playlist doesn't update the playlist (you have to re-open it)
- Adding a magnet to the playlist shows the `Parsing Torrent` notification but doesn't actually add it?  
  
Cheers :)

**Comment by jaruba** [comment]
I'll look into it

**Comment by Vastrix** [comment]
Had any chance to confirm it yet? :)

**Comment by jaruba** [comment]
no, not yet, i've been dedicating my free time on making a beta version of a new Powder product I've been thinking about for the last few months.

**Comment by jaruba** [comment]
Confirmed, fixed both issues, will be available in the next release.

Thanks for reporting them!

**Comment by Vastrix** [comment]
\o/
