### ISSUE TITLE
[Bug] Premature deletion from Cache

### ISSUE THREAD

**Issue by Vastrix** [jaruba/PowderPlayer#140]
Hey,

When watching a video [from magnet] at a certain point [I assume when fully cached/downloaded] when you `seek` to an earlier point in time, the player won't play from the requested position, when checking the cache folder, I saw that it was empty..  
  
Can someone else confirm? :s

**Comment by jaruba** [comment]
cache folder? do you mean you're downloading to the temp directory? what operating system are you using?

**Comment by Vastrix** [comment]
ah no, I meant the Cache folder in `Roaming/powder-player` Wrong folder? :s
Windows :)

**Comment by jaruba** [comment]
@Vastrix Powder does not download to `Roaming/powder-player`, in case you didn't set a custom download folder it will download to the Operating System's temporary folder. Depending on the Operating System, different rules apply for the Temporary Folder, some may delete the data after some time, even before a System Restart.

You can see where the files are downloaded by right clicking the video and going to "Torrent" > "Download Folder". I don't think premature deletion of files is the issue in this case though, it's more likely a timeout of the streaming server, in which case you should just play the video again and it should work.

**Comment by Vastrix** [comment]
> more likely a timeout of the streaming server, in which case you should just play the video again and it should work.  

Ah yea, might indeed be it, I'll close the issue and re-open if that didn't work! :)

Thanks
