### ISSUE TITLE
Playlist sorting

### ISSUE THREAD

**Issue by Jozzyk** [jaruba/PowderPlayer#146]
Can you add a sort by name playlist feature?

**Comment by jaruba** [comment]
I can confirm I've had rare cases myself when this was needed, i'll look into implementing it

**Comment by Jozzyk** [comment]
![1](https://user-images.githubusercontent.com/44834468/48229742-cb639480-e3ca-11e8-9662-fe474995b5fe.jpg)

[Lapsi (1-8) [2018] WEB-DL (1080p).zip](https://github.com/jaruba/PowderPlayer/files/2563746/Lapsi.1-8.2018.WEB-DL.1080p.zip)

For example this torrent in archive.

**Comment by Jozzyk** [comment]
what's new about this?

**Comment by jaruba** [comment]
Playlist sorting has been added to the latest release of Powder Player: https://powder.media/download
