### ISSUE TITLE
Filebrowser text is all boxes

### ISSUE THREAD

**Issue by InvisibleRasta** [jaruba/PowderPlayer#147]
hello, i just installed Powder but when i go to add a torrent all text in the filebrowser are boxes.

**Comment by jaruba** [comment]
I know this issue, it has been fixed before, i think the fix was lost in an update though.

It only happens on one OS though. I think it was Win, what OS are you running?

**Comment by joserick** [comment]
Hi,
I have same problem but in Ubuntu 19.04, I leave you a picture:
[https://i.ibb.co/crXH35q/imagen.png](https://i.ibb.co/crXH35q/imagen.png)

**Comment by jaruba** [comment]
ah, right, it was ubuntu..

download this:
https://github.com/ArchI3Chris/LightTable-Square-Fix/archive/master.zip

and unpack the files from the archive directly into Powder Player's folder

I think it will fix the issue

**Comment by jaruba** [comment]
Please try the latest release of Powder Player: https://powder.media/download

I'll close this issue in the meanwhile, if you still have issues you can reopen it.
