### ISSUE TITLE
Prebuffering stage, do not pass 

### ISSUE THREAD

**Issue by mehdik7** [jaruba/PowderPlayer#149]
I am having problem with Powder Player, I am trying to use ace stream to cast through the Powder Player, it is not loading at all. It is buffering for a while, I do not know if I have to set up or forward port to make it work. Can someone help me out. thank you.

**Comment by jaruba** [comment]
You probably read something wrongly on the site. Powder Player does not support ace streams, it only supports torrents and youtube-dl sites.

I don't know if I'll ever add ace stream support to Powder Player.

Powder Web (a different project) supports ace streams, sopcast, torrents, youtube-dl and local files.
