### ISSUE TITLE
[Bug] Selecting "No" in  the "Would you like to remove the downloaded files" dialog, still deletes the files.

### ISSUE THREAD

**Issue by lalibi** [jaruba/PowderPlayer#150]
Just what the title says.

**Comment by jaruba** [comment]
What makes u think it does not delete it? Are u setting a custom download path? As otherwise it downloads to Temp. (which is by design temporary)

**Comment by lalibi** [comment]
It's the other way around. It deletes the files, although I click "No". I've even tried to click "Yes" just to see if the buttons are mixed up. 

I tested it again a few minutes ago, no matter what button I press on this dialog, the folder in the `%TEMP%\Powder-Player\torrent-stream` path gets cleared.

**Comment by jaruba** [comment]
Can you try setting a custom download path too and testing again?

Does this happen in the currently released version or the test version I linked?

**Comment by lalibi** [comment]
With both versions, the behavior is the same.

But, as you suggested, when setting a custom download path, it works as expected.

**Comment by jaruba** [comment]
Then I don't think it's really a bug, the default is the data being "temporary" anyway. Wether it's less or more temporary.. does that really matter?

**Comment by lalibi** [comment]
It makes sense, I wasn't aware someone could change the downloads folder. Although, it took me a  while to find this option, since there is a different set of settings on the first screen of the player.

I am closing the issue.
