### ISSUE TITLE
[Bug] Chromecast casting never really works

### ISSUE THREAD

**Issue by lalibi** [jaruba/PowderPlayer#151]
I know that this is probably something that has to do with my setup, but so far I haven't been able to make casting work with Powder Player, not even once. Most of the time the "_Device List_" is empty, and when it's not, it just freezes at the "_Connecting_" or "_Buffering_" stage.

To be honest, most programs I've tried fail regularly, only "Airflow" works consistently.

I'm using Chromecast 2rd gen. Is this something that happens to others as well, or is it just me?

**Comment by jaruba** [comment]
I've made some advancements regarding Chromecast / Airplay casting some time ago, but never got to releasing them.

I'll check over my research / implementation, it might make all the difference. But casting can be a complex and touchy subject, I can't be sure it will solve the issues you're currently encountering.

**Comment by jaruba** [comment]
Try this new test version, see if it fixes your Chromecast issues:
https://github.com/jaruba/PowderPlayer-Test/releases/tag/v0.0.3

**Comment by jaruba** [comment]
@lalibi Please try the latest release of Powder Player: https://powder.media/download

I'll close this issue in the meanwhile, if you still have issues you can reopen it.
