### ISSUE TITLE
Torrent video doesn't play

### ISSUE THREAD

**Issue by Mystic-Mirage** [jaruba/PowderPlayer#152]
Hey!

I've got an error bellow when trying to play some video. I see thumbnails, video length and it seems download in the process but no video.
```
undefined:1
Redirecting to https://powder.media/metaData/get.php?f=The.Walking.Dead.S10E08_%5Bscarabey.org%5D.avi&h=950e26fd6eb4ce39f432405d7c9d080d9b85795f&s=860418048 (308)
^

SyntaxError: Unexpected token R
    at Object.parse (native)
    at /home/mm/PowderPlayer/resources/app.asar/js/components/Player/workers/subtitles/find.js:1:4065
    at done (/home/mm/PowderPlayer/resources/app.asar/node_modules/needle/lib/needle.js:357:7)
    at PassThrough.<anonymous> (/home/mm/PowderPlayer/resources/app.asar/node_modules/needle/lib/needle.js:546:9)
    at emitNone (events.js:85:20)
    at PassThrough.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by Mystic-Mirage** [comment]
I've disabled "Find subtitles" option but no luck. Seems the playback problem doesn't relate to traceback above.

**Comment by jaruba** [comment]
That's definitely not good.. I'll look into it.

**Comment by jaruba** [comment]
I've fixed the response on the server, so it should work now.

I'm also actively working on a new version that will be released very soon which stops using those API endpoints all together.

**Comment by jaruba** [comment]
Here is the test version for the future release, if you wish to test it:
https://github.com/jaruba/PowderPlayer-Test/releases/tag/v0.0.3

**Comment by Mystic-Mirage** [comment]
@jaruba Thank you! Do you have that version for Linux?

**Comment by jaruba** [comment]
Unfortunately not, I intentionally avoided building a Linux version for this test, as it's a bit more complex to build it correctly for Linux.

So a Linux version will only be available with the official release. Which will be very soon if this test version goes well.

**Comment by jaruba** [comment]
Please try the latest release of Powder Player: https://powder.media/download

If you still have issues you can reopen it.

**Comment by Mystic-Mirage** [comment]
It works! Thank you!

**Comment by jaruba** [comment]
@Mystic-Mirage Glad to hear it!
