### ISSUE TITLE
Progress Bar for Local Video Files does not Work Properly

### ISSUE THREAD

**Issue by kvirusp** [jaruba/PowderPlayer#17]
Progress bar when playing local files is glitchy.. does not work propperly in full screen allso why is it showing me it's buffering ?

**Comment by jaruba** [comment]
When you say glitchy, are you referring to when you click it and it goes back then forward again?

I agree I should remove the buffering bar for local videos.

**Comment by jaruba** [comment]
You should also download v0.11:
https://github.com/jaruba/PowderPlayer/releases

And re-associate your files / magnet links in the settings (if they wore previously associated). It has quite a few important fixes.
