### ISSUE TITLE
Video Title is wrong when Multiple Files are Dragged and Dropped

### ISSUE THREAD

**Issue by kvirusp** [jaruba/PowderPlayer#18]
when multiple files are dragged and dropped in order to activate the playlist function, that still doesn't work properly, the name of the window is not the name of the file currently playing

**Comment by jaruba** [comment]
Is it the name of the last file in the playlist?

**Comment by kvirusp** [comment]
yup

**Comment by jaruba** [comment]
Makes sense, good catch!
