### ISSUE TITLE
Add an Intelligent Library

### ISSUE THREAD

**Issue by kvirusp** [jaruba/PowderPlayer#20]
a library function would also be nice with a refresh or scan function.
Once you setup a folder (for example your default torrent download folder) and the user manually sets up a "custom playlist" lets say named My-Legal-Video you select a sample or "start" episode.
After that when you click refresh/scan the program would search your default folder for files with names similar to the sample taking into account file names and details.
For example for  "my-legal-video.315.hdtv-lol.mp4" added as sample, once you click scan if in the default folder, the file named "My-Legal-Video.S03E16.720p.HDTV.X264-DIMENSION" will be added to the playlist.

**Comment by jaruba** [comment]
I'm pretty sure this can be done with a Natural Sort Algorithm
