### ISSUE TITLE
Shutdown / Pause Timer

### ISSUE THREAD

**Issue by kvirusp** [jaruba/PowderPlayer#22]
Often times i find myself searching for a TV show to binge-watch while i drift to sleep (more often than not while drunk), two problems appear,first it takes too long to download 2-3 episodes of something boring enough, secondly  if i drop a magnetlink for a season of something i won't get any sleep because eventually it's going to start bothering me.
Simple fix, i think, would be to introduce an option to stop or pause play after a set amount of time.

Ty in advance,
Sincerely drunk as always, kvirusp.

**Comment by jaruba** [comment]
Sounds like your requesting a Sleep Timer.

**Comment by kvirusp** [comment]
Don't belittle my request and or phrasing, "shutdown/pause timer" :octopus:

**Comment by jaruba** [comment]
A Sleep Timer feature has been added to Powder Player v0.16, you can download it from: http://powder.media/
