### ISSUE TITLE
Hide Window Frame when not Hovered

### ISSUE THREAD

**Issue by kvirusp** [jaruba/PowderPlayer#3]
window around player should fade in/out on hover

**Comment by jaruba** [comment]
This is quite a bit harder then first anticipated. I would have to draw the entire Frame in HTML+CSS myself to be able to do this, it isn't possible with the Default OS Window Frame.

Issue posted at nw.js: https://github.com/nwjs/nw.js/issues/3200

**Comment by kvirusp** [comment]
Good luck with that ;)

**Comment by jaruba** [comment]
done, will be available in the next version.
