### ISSUE TITLE
How do I install PowderPlayer ?

### ISSUE THREAD

**Issue by jounlye** [jaruba/PowderPlayer#33]

**Comment by jaruba** [comment]
Did you manage to install it? :)

One way would be to just download the binary from https://github.com/jaruba/PowderPlayer/releases

This is an old version that uses WebChimera Plugin though, I'm will release the new version soon that uses WebChimera.js and has many more features. If you want to try the next version now, you could follow the [Building Instructions](https://github.com/jaruba/PowderPlayer/wiki)
