### ISSUE TITLE
Use Trakt API for Episode Tracking

### ISSUE THREAD

**Issue by jaruba** [jaruba/PowderPlayer#34]
Integrate the Trakt API for Movie/Episode Tracking and an Advanced History Feature.

Users that want to use these features will require a Trakt Account.

(this might be best made as an extension instead of a default feature)

**Comment by Breaking1** [comment]
Extension or feature as long as it get implemented we're happy. :+1:

**Comment by samukets** [comment]
default feature for me is the best choice...

**Comment by jaruba** [comment]
Powder Player Nightly Pre-Release now supports Trakt Scrobbling.

The official announcement for Powder Player Nightly Pre-Release and the download link can be found here:
https://www.reddit.com/r/PowderPlayer/comments/4ralk2/powder_player_v100_prerelease_available_for/
