### ISSUE TITLE
Chromecast Support

### ISSUE THREAD

**Issue by jaruba** [jaruba/PowderPlayer#36]

**Comment by Breaking1** [comment]
+1

**Comment by pepijn809** [comment]
Absolutely! +1

**Comment by jaruba** [comment]
Uhm, I was planning on releasing v0.95 very soon after 3 months since the last version. It has some amazing new features, a lot of minor and a few major bug fixes.

Chromecast is popular though and it has been requested before. I have a Chromecast around the house and I have the infrastructure for casting already made from DLNA/UPNP casting.

So now I'm faced with making a choice between releasing the new version sooner or postponing it for about 2 more weeks in an attempt to get basic Chromecast support working too.. :/

I've postponed it for so long though, but you are the users, if you think Chromecast is important, your will is my command. :)

**Comment by Breaking1** [comment]
Hi.
Thank you so mutch for your reply.

I'm more than happy to wait 2 more weeks or longer to get CC support.(Sorry to all of you who don't have it.But it's cheap so start saving and you will have one when he's ready!)

But yeah most of my stuff get watched on the big screen from my CC. 

So for me this is the key thing,if it had the CC support it would probably already be my 1 choice for streaming torrents/magnet links to the big screen.

**Comment by jaruba** [comment]
Cool, I'll try implementing it after I'm done with the feature I'm currently working on.

If it proves to be more complicated then I expect I'll have to postpone it, otherwise basic support should be ready in the next release.

The only issue I see with this is that I have to implement transcoding to convert all video types to HLS or mp4 as Chromecast doesn't really support anything else.

Btw, what OS are you on and how important is subtitle support on Chromecast for you? :)

**Comment by Breaking1** [comment]
Sounds really great. :+1: 

Subtitles can wait,if we get basic support then you can work on the other things.But at some point i would probably want subtitles too :smiling_imp: 

If we just know that they are coming,who knows maybe we even get tired of waiting and know some skilled dev's who can help you out on the project.Who knows what could happen here,

And i'm running windows with my CC,easiest for the other familly members who didn't know that there existed OS that didn't have the name windows in it.

**Comment by jaruba** [comment]
I'm thinking this: https://github.com/TorrenTV/TorrenTV/issues/88

If I could get it working like that, it would give a proper start to casting for Chromecast / Airplay / Roku.

**Comment by Breaking1** [comment]
:+1:

**Comment by entr** [comment]
What about how popcorn(now butter) does it?

**Comment by jaruba** [comment]
@entr I haven't had time to look at their code yet.

**Comment by kodaxx** [comment]
Yessss....this would be amazing!!

**Comment by luigiplr** [comment]
@entr Magics.

**Comment by Breaking1** [comment]
@jaruba  do you have a minute to update us on the progress on this feature?

**Comment by jaruba** [comment]
Atm, me and @luigiplr are working on rewriting Powder Player completely for Electron and React while @Ivshti is posting Hitler pics on our commits.

Proof of madness:
https://github.com/jaruba/PowderPlayer/commit/af9255765996138b249fd7edc4515b38df5be256
https://github.com/jaruba/PowderPlayer/commit/f0bfd66d96355f8fa5f2e8122ab0d2e3eda5151c#commitcomment-14621001

@matbee is working on a magical remuxing module to make our transcoding needs for casting a breeze.

This React version we're working on is a lot faster and seems to have smoother playback. I'm a bit split between making Chromecast for Powder's current code then remaking it for the React version or to push more work on the React version and writing it there directly.

I guess it all comes down to even releasing v0.95 or working on v1.0

**Comment by jaruba** [comment]
@acidhax

**Comment by acidhax** [comment]
I shall complete my mission and bring forth a future of pain-free remuxing.

**Comment by jaruba** [comment]
![60366520](https://cloud.githubusercontent.com/assets/1777923/11407552/32317d1a-93bc-11e5-82e0-950aa64ee328.jpg)

**Comment by luigiplr** [comment]
This is how I picture @acidhax ![](http://img.pandawhale.com/42570-474drivemecloseriwanttohitthem-AJDN.jpeg)

**Comment by Ivshti** [comment]
> Atm, me and @luigiplr are working on rewriting Powder Player completely for Electron and React while @Ivshti is posting Hitler pics on our commits.
> @acidhax is working on a magical remuxing module to make our transcoding needs for casting a breeze.

Well this sounds like a circus - hitler pics, magic modules.

@acidhax how would that module work so that it can transcode/transmux from an HTTP stream and not a full file? HLS?

**Comment by acidhax** [comment]
It'll request streams of a specific byte range. It's quite simple! I'll show more when I publish the module.

**Comment by jaruba** [comment]
> Well this sounds like a circus - hitler pics, magic modules.

Have no fear @Breaking1 , @Ivshti is just joking around, this will be solved by (most probably) some of the most qualified people in the world for this. :)

We're pros, we just like having fun while working.

**Comment by luigiplr** [comment]
>We're pros, we just like having fun while working.

![](http://opbeat.files.wordpress.com/2012/08/fisi_640.jpg)

**Comment by Breaking1** [comment]
Hahaha @jaruba  no worries,if you guys rob a bank while you do this i don't give a f... as long as you have fun and get the job done :+1:

Great to see there's no lack of activity and qualified people working on it,gives me  more confidence in that this will be my future torrent media player.

**Comment by luigiplr** [comment]
Oh hi @breaking1 been a while xD

**Comment by Breaking1** [comment]
Yeah @luigiplr it has,nice to see you again xD

@pepijn809 was actually the guy who was kind enough to point me here,so i could bug you guys and catch up on the latest Hitler pics xD

**Comment by luigiplr** [comment]
You two want to join magics? Slack chat we run for stuff like this :)

**Comment by Breaking1** [comment]
Sure,i'd love to be a part of the fun stuff and watch the magic happens xD

I'm familiar with Slack, we used it alot for the popcorntime team chat.

**Comment by luigiplr** [comment]
Emails pls.

**Comment by Breaking1** [comment]
Fucking great,here you go toreaj@hotmail.com

@pepijn809 doesn't trust his email with me he's just affraid ill find and stalk his girlfriend.

**Comment by luigiplr** [comment]
@Breaking1 i invited the email you posted prior :P

**Comment by pepijn809** [comment]
@luigiplr
Sounds cool man, and damn that breaking does stalk my like not exisiting girlfriend currently. 
He be crazy man :p

But, i'm definitely interested in helping out. 

Pepijn809@gmail.com is my e-mail,  Pls dont't stalk me girlfriend ^©^

**Comment by jaruba** [comment]
@pepijn809 invited and spoofed your email.

**Comment by Breaking1** [comment]
@luigiplr yeah i know,since it was my private email,i changed it after receiving the invite.

**Comment by Ivshti** [comment]
Btw someone mentioned Connect SDK somewhere - http://connectsdk.com/
Yes, it's only android/ios, but it appears good, and we can learn a ton from it.

**Comment by jaruba** [comment]
@Ivshti 

> Btw someone mentioned Connect SDK somewhere

Here: https://github.com/jaruba/PowderPlayer/issues/51#issuecomment-154504139

**Comment by Ivshti** [comment]
This "web app bridge" literarily has nothing to do with what we need. "JavaScript bridge" just means something to control/interact with the connect sdk, not a way to use it through anything nw/electron-based.

**Comment by jaruba** [comment]
I think the web app thing can be used for casting videos, but remote control from the tv won't work so it's useless anyway. This sparked my curiosity though:
https://github.com/ConnectSDK/Connect-SDK-Windows

But I didn't get around to playing with it yet.

**Comment by jaruba** [comment]
The thing is, if they really do have a functional library for windows, and if it can be built for the other platforms too.. Wouldn't it be possible to make it into a node.js native module?

If Connect SDK could be built as a native module it would be a total game changer for casting.

**Comment by Ivshti** [comment]
I saw that, you may have noticed I starred it.

"if they really do have a functional library for windows, and if it can be built for the other platforms too" - same goes for android/ios. Windows is no different, it's all the same principle

"Wouldn't it be possible to make it into a node.js native module?" - nope, that's C#

**Comment by jaruba** [comment]
"you may have noticed I starred it."

I did not notice that, but I have found this post on the author's blog about that repo:
http://sorin.serbans.net/blog/2015/08/connectsdk-windows/507/

It's pretty far from what we need..

**Comment by acidhax** [comment]
.net core exists now ;)

**Comment by luigiplr** [comment]
>.net core exists now ;)

![it's happening](http://i.imgur.com/vwMin.gif)

**Comment by samukets** [comment]
Some prevision about this feature release?

**Comment by samukets** [comment]
Maybe analysis popcorn time git is a good idea...

**Comment by luigiplr** [comment]
>Maybe analysis popcorn time git is a good idea...

ENHANCE

**Comment by YIFYtorrents** [comment]
so you want to rip some of our popcorn time code. No problem dude you are welcome.

**Comment by jaruba** [comment]
@samukets @YIFYtorrents + others that recommended this

There's no need to rip anything from anywhere, we're making our own thing.. I already streamed to Chromecast, supported and unsupported files (by transcoding) thanks to the efforts of @acidhax and @SchizoDuckie .

It's just a question of how to fit it best in Powder's code now.

**Comment by YIFYtorrents** [comment]
just kidding dude. I really recommend popcorn time's chromecast library. Check it out and copy whatever you want: https://github.com/PopcornTimeCommunity/desktop/blob/master/src/app/lib/device/chromecast.js

**Comment by samukets** [comment]
we are family :+1: , LOL uhuhau

**Comment by jaruba** [comment]
Powder Player Nightly Pre-Release now supports Chromecast with subtitles and advanced subtitle features. Airplay and Advanced DLNA support is also available.

The official announcement for Powder Player Nightly Pre-Release and the download link can be found here:
https://www.reddit.com/r/PowderPlayer/comments/4ralk2/powder_player_v100_prerelease_available_for/

I tested it on an older Chromecast. (not the new version)

If any of you test it too, please make sure to tell me how it went as it still needs more testing.
