### ISSUE TITLE
Video/application "on top" - feature request

### ISSUE THREAD

**Issue by streger** [jaruba/PowderPlayer#41]
Haven't found this option anywhere (in shortcuts, in options) and it would definitely be useful feature to have. 

Node webkit has this with setAlwaysOnTop I guess.
https://github.com/atom/electron/blob/master/docs/api/browser-window.md#winsetalwaysontopflag

**Comment by streger** [comment]
My bad :( 
Found it on the context menu.

**Comment by jaruba** [comment]
Powder Player has so many features atm that it's sometimes hard to make them all easily visible or understandable. :)

For example, when the window is set to always on top and the mouse isn't moving, the window frame fades out (this only happens on Windows and Mac though). More interesting still is that if the window is close to one of the top corners of the screen, then it will stick to that screen corner when the frame disappears. This can be seen in the short demo video: https://youtu.be/8tuFLQcjfMg?t=57s

Although unrelated, you should also check out the hotkeys to discover some more of the player's interesting features: https://github.com/jaruba/PowderPlayer/wiki/Hotkeys
