### ISSUE TITLE
Fetch meta for playlist media

### ISSUE THREAD

**Issue by luigiplr** [jaruba/PowderPlayer#42]
Images from trakt.tv/fanart.tv
Synopsis from tvdb (translated) or english trakt.tv

**Comment by jaruba** [comment]
where would this fit in the GUI?

**Comment by jaruba** [comment]
I mean, I've thought about it before ofc, but..

- starting from a magnet link is most of the times very fast, and checking APIs, downloading images, etc would need to be done in the same time as it downloads the torrent, as that's when it has a magnet link

- when prebuffering, powder is downloading at max speed which might create network flooding (for slow connections or even good connections on wi-fi), which practically means that there is a high chance that all the APIs we try to connect to will end in a connection timeout and would make remote image loading impossible too

- images, synopsis, etc. are usually useful before you decide to watch something, as powder does not know what you will watch before you actually start it with something, all this information will lack importance if it's gotten when it already started streaming

**Comment by luigiplr** [comment]
it would possibly have a use on the pause screen? or be used in the header (title) also the requests are very small.

primary use would probably be for multi file torrents (aka season/complete) in providing a netflix/popcorn time like experience for selecting your episode.

**Comment by jaruba** [comment]
> primary use would probably be for multi file torrents (aka season/complete) in providing a netflix/popcorn time like experience for selecting your episode.

i love the idea of changing the playlist gui :)
