### ISSUE TITLE
Support custom file protocol?

### ISSUE THREAD

**Issue by iadj** [jaruba/PowderPlayer#43]
A cool feature would be supporting a custom protocol (i.e. `powder://[hash]`), that automatically opens the client & streams the torrent hash. I use a different torrent client for the magnet protocol, so having another separate protocol for PowderPlayer could prove to be useful.

**Comment by jaruba** [comment]
I've thought about it, although i was thinking of something like ``pow://[hash]``. :)

The problem with this is that it would still need to be associated manually, as associations need admin rights on most operating systems.

I've not given up on finding some way of doing it on installation though..

**Comment by jaruba** [comment]
Related to this, I was also thinking of making an option in the settings where the user can disable non-media torrent downloading.

So if it's associated with magnet links, if it does find any video or audio files to play in the torrent, it just downloads the torrent, opens it with the default torrent file application then closes itself.

**Comment by iadj** [comment]
Playback (https://github.com/mafintosh/playback) has built-in protocol support for OSX. The protocol isn't supported on Windows though but it might be good for reference.

There are Windows installers that request admin rights to achieve something like adding a custom protocol. I wonder if someone managed to get this working with Electron or as a package?

**Comment by Ivshti** [comment]
I did, [Stremio](http://strem.io) supports protocol associations for Windows & Mac (stremio://) 

I used an NSIS installer, using some scripts for NSIS I found on the internet by mere googling.

http://nsis.sourceforge.net/Application_Association_Registration_plug-in

**Comment by jaruba** [comment]
I'm not worried about Mac and Windows..

Mac doesn't need admin rights to associate, as more apps can associate with the same files and protocols..

Windows can safely do this in the installation process by just hacking and slashing through the registry.. Even if the installer would need admin rights, it's still ok..

On Linux though, I need to request the sudo user and password to do this, and it would be a bit weird to get prompted for the admin user name and pass when you start powder for the very first time.. but i may not be so bad if i ask nicely.. :P

**Comment by Ivshti** [comment]
Yes. 

In Linux it's expected that there would be packages for the apps which will also add the desktop file and therefore handle associations. 

However it can't be expected of us as app developers to arrange that happening for every distro.

For now you (and me) can put a desktop file in the tar gz, and expect users to figure it out - they are Linux users after all. Also note it in a README or the website

**Comment by jaruba** [comment]
I'll look around at how I can make a `.deb` and make a fallback to a script file that associates on very first open if the desktop file is not found..

**Comment by jaruba** [comment]
Did some research, I think I've found all I need to get this working, will try to add it in the next release.

**Comment by jaruba** [comment]
I've added association to the `pow://` protocol (it will be available from the next version: v0.95), on Windows it will associate when you install the app, on Mac it associates the very first time you start the app, on Linux association is optional, and is done through a button in the settings (mainly "Associate with Powder Links")

URI scheme examples:

```
pow://19288989fd99a41ad24f30c23b0271e0a825ac5f
```

or:

```
pow:?xt=urn:btih:19288989fd99a41ad24f30c23b0271e0a825ac5f&dn=Sintel&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Fexodus.desync.com%3A6969
```

^ these will both work

More so, you can pass any of the [command line arguments](https://github.com/jaruba/PowderPlayer/wiki/Command-Line-Args) through the URI Scheme, so it's possible to do:

```
pow://19288989fd99a41ad24f30c23b0271e0a825ac5f&title=My%20Cool%20Title&fs
```

or:

```
pow:?xt=urn:btih:19288989fd99a41ad24f30c23b0271e0a825ac5f&title=My%20Cool%20Title&fs
```

There are some other cool things that can be done with powder links, like sending a secret, port, etc. so you can authenticate with the powder instance (with the user's permission ofc) so you can use the websocket api with it (that will let you know playback position, when playback ended, etc)

**Comment by iadj** [comment]
Amazing! Fast and efficient integration. Good job @jaruba

**Comment by jaruba** [comment]
@iadj I'm planing to release version `0.95` in the next few days. I'm pretty much done with all the new features, I just have to tinker with the values a bit more. :)
