### ISSUE TITLE
Running problems

### ISSUE THREAD

**Issue by Skruf90** [jaruba/PowderPlayer#44]
Hi. 
I followed the instructions for linux distros with apt support. I cloned repository and did npm install etc. Then extracted files from nwjs-v0.12.2-linux-ia32 to the folder containing node_modules, scr etc. 

I then try to run nw, but nothing happens. 

Any solution :)?

**Comment by Skruf90** [comment]
Nvm, haha. Downloaded 32-bits nwjs. Downloaded 64-bits all good.

**Comment by jaruba** [comment]
yeah, ftm Powder Player works on 64 bit on linux, 32 bit is not impossible, but just very low priority as very few actually users have 32 bit linux. There is only one dependency that is architecture specific though (webchimera.js that we use to draw the video frames with webgl) :)

**Comment by jaruba** [comment]
i just realized that i linked to nw.js 32 bit on the linux building guide, i will change that imediately, thanks :)

**Comment by Skruf90** [comment]
Thats good :)
