### ISSUE TITLE
Drag & Drop Magnet Links into Powder doesn't work

### ISSUE THREAD

**Issue by Draxler** [jaruba/PowderPlayer#47]
Win OS

I'm not completley sure if this function was implemented for Magnet files in the first place.
Anyway, if it was; **Drag & Drop** for Magnet files is not working. Nothing happened when 
magnet file is drop into Powder app.

**Comment by jaruba** [comment]
What do you mean by "Magnet Files"? Could you please elaborate? Aren't `.torrent` files the "file version" of Magnet Links?

**Comment by jaruba** [comment]
Uhm, I think I have an idea of what your trying to do, are you by any chance keeping click pressed over a Magnet Link button, then dragging that Magnet Link to Powder Player's window and dropping it?

If so, then yes, that doesn't work, as drag and drop is made for files, not links.. I didn't even think dragging and dropping links was possible, but searching around the internet I did find some techniques of making drag and drop work for links too. I think dragging and dropping links would indeed be useful for Powder Player and I will try to add this feature to the next version.

In the meanwhile, the method of using Magnet Links with Powder is as follows:

**Step 1**

Right click a Magnet Link button, and press "Copy link address"

![step-1](https://cloud.githubusercontent.com/assets/1777923/10607724/1b33c03a-7744-11e5-9f8c-9da88be0cd10.png)

**Step 2**

Go to Powder Player's window and press "Use a URL" from the Main Menu screen (alternatively, if your already playing a video, you can open the playlist menu and press "Add URL")

![step-2](https://cloud.githubusercontent.com/assets/1777923/10607757/61a0e854-7744-11e5-8e9a-8b7259d0c918.png)

**Step 3**

Either Right Click the input field or use ``CTRL + V`` to paste the Magnet Link, then press "Stream"

![step-3](https://cloud.githubusercontent.com/assets/1777923/10607788/911ebe8a-7744-11e5-9ab7-3b0f79bee66f.png)

**Comment by Draxler** [comment]
sorry; it's magnet links not files

**Comment by jaruba** [comment]
Cool, that makes sense! :)

I'll try to add this feature in the next version. I'll hopefully release it in the next few days if everything goes well. :dancer:
