### ISSUE TITLE
Linux Mint: Sound cuts off when seeking

### ISSUE THREAD

**Issue by sroerick** [jaruba/PowderPlayer#49]
Sound works find when loading a video.

Track to a new part of video, silence.

On linux mint

**Comment by jaruba** [comment]
What steps would I have to follow to get this problem? Also, what extensions do the files have? Are they by any chance `.avi` files?

**Comment by sroerick** [comment]
found more detailed behavior: the issue comes when the video is not buffered. If a section of the video buffers, and I track to that, there is sound. if there is no video buffered or I seek to a new place in the video, sound cuts out.

**Comment by jaruba** [comment]
What version is the VLC you have installed? Can you try updating it?

**Comment by jaruba** [comment]
Atm there is an issue with embedding a custom VLC version inside the app, so it's using the VLC you have installed on your system, there is a chance this is a VLC issue that may be fixed in future versions.

**Comment by sroerick** [comment]
2.21, and the files are MP4

**Comment by sroerick** [comment]
behavior can be reproduced, at least on my computer, by opening a new file and seeking to pretty much any point

**Comment by sroerick** [comment]
VLC is latest version

**Comment by sroerick** [comment]
Also running into the issue when the video needs to buffer. 

video pauses, buffering message comes up, video starts again without sound

**Comment by jaruba** [comment]
I just tried it with a torrent that has a `.mp4` file in my Ubuntu VM, with VLC 2.2.0, I didn't get the issue. Could you help me out with getting the debug log of VLC from inside Powder Player?

You would need to open `/PowderPlayer/node_modules/pw-wcjs-player/index.js` then go to the line `610`, you should see something like:

    if (wcpSettings && wcpSettings["vlcArgs"]) vlcs[newid].vlc = vlcs[newid].renderer.init(wjs(newid).canvas,wcpSettings["vlcArgs"]);
    else vlcs[newid].vlc = vlcs[newid].renderer.init(wjs(newid).canvas);

you would need to change it to:

    wcpSettings["vlcArgs"].push("--vvv");
    
    if (wcpSettings && wcpSettings["vlcArgs"]) vlcs[newid].vlc = vlcs[newid].renderer.init(wjs(newid).canvas,wcpSettings["vlcArgs"]);
    else vlcs[newid].vlc = vlcs[newid].renderer.init(wjs(newid).canvas);

To turn on VLC's verbose mode. Then, just go to Powder Player's folder with the terminal and run it with `./powder`, this should print the logs in the terminal. Then just reproduce the issue with that player instance and copy + paste the log here.

**Comment by sroerick** [comment]
getting this: when i run 

ATTENTION: default value of option force_s3tc_enable overridden by environment.
vlc: unknown option or missing mandatory argument `--vvv`

also tried --verbose

**Comment by jaruba** [comment]
Sorry, that was my fault, i think it should be `-vvv`, not `--vvv` :(

**Comment by jaruba** [comment]
@sroerick did you have time to test this yet? I'll release a new version soon and I'd like to see if this is fixable too for it.

**Comment by sroerick** [comment]
I haven't yet: but the issue is not with powder player, it happens with VLC as well I discovered.

would you still like me to test?

**Comment by jaruba** [comment]
That makes sense, you should try an older version of VLC..

In the worst possible case, if older versions don't work either, and this is a big issue for you, then try VLC Nightly. (although this is always their most unstable version, but it always fixes the most bugs in the present version)

If you fix VLC, considering your on Linux, Powder will also be fixed along with it. Unfortunately, there is nothing I can do from my side to fix this.. so the issue should be closed.

If you do have time to test though, and find a version that works, it would be nice to post the version you found working here for future reference if others will also run into this issue. :)
