### ISSUE TITLE
Please Release the New Version

### ISSUE THREAD

**Issue by luigiplr** [jaruba/PowderPlayer#52]
![FUCKEN](http://i.imgur.com/3F6ad8m.png)
![SLOTH](http://i.imgur.com/0IMAcKh.png)
![WAS HERE](http://i.imgur.com/zMeBTb6.png)

**Comment by jaruba** [comment]
Why thank you, Riddler.

http://img4.wikia.nocookie.net/__cb20140128214050/villains/images/a/a6/Riddler_(Batman_Forever).jpg

**Comment by Draxler** [comment]
@jaruba 

lol  :+1:

**Comment by luigiplr** [comment]
Haqhahhaha :ok_hand:

**Comment by vankasteelj** [comment]
common jaruba, release da shiet!

**Comment by jaruba** [comment]
@vankasteelj 

![i-have-no-idea-what-im-doing_o_99475](https://cloud.githubusercontent.com/assets/1777923/11172587/6f1b9eba-8c12-11e5-883c-fad60d5834ff.jpg)

**Comment by vankasteelj** [comment]
![sad-dog](https://cloud.githubusercontent.com/assets/12599850/11172614/8216bc96-8c0a-11e5-86e4-3544ee714487.png)

**Comment by luigiplr** [comment]
:dancer:

**Comment by luigiplr** [comment]
![](http://i.imgur.com/wWTaNpi.png)

![](http://tribzap2it.files.wordpress.com/2014/06/chris-pratt-gif-2.gif?w=500&h=318)
