### ISSUE TITLE
Auto-download Subtitles for VLC player

### ISSUE THREAD

**Issue by spiritson** [jaruba/PowderPlayer#53]
Currently, the auto-download subtitles works for internal player, but the feature is not available with VLC player. One way of implementing this could be:

A secondary UI window could be opened and shown, once the preferred subtitles are selected and downloaded, it can be dragged and dropped into VLC player. 

This saves the user lot of manual work of going to the web and downloading subtitle on his/her own while using VLC. This also does not sacrifice speed and both the video play and auto downloading of subtitle can happen in parallel.

Courtesy: Gitter chat between me and @jaruba

**Comment by jaruba** [comment]
Totally gonna do it, just need to finish some crucial new features first. :)

**Comment by spiritson** [comment]
:+1:

**Comment by juanej** [comment]
Any news on this?

**Comment by jaruba** [comment]
@juanej It's not hard to do, but due to the heavy development of the Nightly that needs to be released as soon as possible, this will need to be delayed further.

**Comment by jaruba** [comment]
It is now possible to cast to DLNA, Chromecast, Airplay, the Browser, other Players, Friends, etc. with subtitles (but only with Transcode set to "Yes") in Powder Player Nightly. You can also set subtitle size, color and position.

I will also attempt to make subtitles work with other players without transcoding in the future, but this is all I got for now..

The official announcement for Powder Player Nightly Pre-Release and the download link can be found here:
https://www.reddit.com/r/PowderPlayer/comments/4ralk2/powder_player_v100_prerelease_available_for/
