### ISSUE TITLE
Linux: HiDPI support

### ISSUE THREAD

**Issue by pguth** [jaruba/PowderPlayer#54]
I have a 3200x1800 px screen and the player appears super small. Similar screens get more common over time, I guess :)

![hidpi](https://cdn.pbrd.co/images/25bCAjLq.png)

**Comment by jaruba** [comment]
That's hilarious... :))

Could you please type `CTRL` + `D` to open the developer console, and with the `Console` tab activated type:

```
win.gui.zoomLevel = 2
```

Tell me if the size is ok with the new zoom level, or play with the value until you find the best size. You can play set fractions too (such as `1.7`, `3.2`). I'd need to know the zoom level that would be best for such resolutions. (if `win.gui.zoomLevel` doesn't work, try `win.zoomLevel` instead)

**Comment by pguth** [comment]
Wow, quick response time :-)

`3` feels like a sensible value for my resolution:

![zoomLevel 3](https://cdn.pbrd.co/images/26PAqJAB.png)

That's it with `2` (since I feel that's a bit of a design decision):

![zoomLevel 2](https://cdn.pbrd.co/images/26PiCd6W.png)

But it's really funny how the developer console looks :D

![developer console](https://cdn.pbrd.co/images/26PpFtFZ.png)

**Comment by jaruba** [comment]
Cool, I'll do the math of how much it should increase the app size depending on screen size based on your resolution and the top most accepted resolution for the current default size. :)

**Comment by jaruba** [comment]
I've looked into the matter a bit and had a friend test powder out on a resolution of 2880x1800. On Mac and Windows 10 it was fine (the app window resized itself accordingly on it's own).

I now believe this is a linux only issue and is most probably this issue in Chromium:
https://code.google.com/p/chromium/issues/detail?id=143619

With this said, I can force `zoomLevel` only on Linux but the right click context menu and the developer console will still be ridiculously small until Chromium gets it fixed.

**Comment by jaruba** [comment]
I've added a setting for zoom level (up to level 4) in the main menu. Using it will change the default zoom level of the app.
