### ISSUE TITLE
Option to change the buffer size

### ISSUE THREAD

**Issue by cocodrino** [jaruba/PowderPlayer#57]
Hi @jaruba  Iḿ really happy with powder player right now, it works perfect but I've a not so fast internet connection, so I experiment several interruptions for buffer actions, I think than in my case would be nice a bigger buffer size, is it possible give this option or than maybe I can change some code and could increase the buffer?..thanks!

**Comment by jaruba** [comment]
Yes, this is possible. I can make an option to set the buffer size and you can also change it from the code if you want.

The default buffer size is set to 10 seconds, the minimum buffer size can be 0 milliseconds and the maximum is 1 minute.

To change it yourself from the code you would need to open `PowderPlayer/node_modules/pw-wcjs-player/index.js`, search for the lines:

```
    // set default network-caching to 10 seconds
    if (!wcpSettings["buffer"]) wcpSettings["buffer"] = 10000;
```

and set it from 10000 (ms = 10 secs) to anything between 0 and 60000.

**Comment by vankasteelj** [comment]
@jaruba how do you link MB to secs? (and you might close this)

**Comment by jaruba** [comment]
I don't, VLC does.

**Comment by cocodrino** [comment]
ups, sorry for the delay, thank so much @jaruba, extending it to 60000 makes much more smoth my streaming, is it not possible increase even more?....

**Comment by jaruba** [comment]
@cocodrino

Unfortunately not, this is the maximum that the embedded VLC can handle.

What you could try though is to go in the Settings Menu in Powder's Main Menu (the gear icon in the upper right corner) then click Torrent Settings and disable Speed Pulsing.

This might increase download speed but it will also guarantee that in some cases the internet won't work anymore as the torrent downloading will use the maximum speed it can from your connection.

**Comment by cocodrino** [comment]
thank so much @jaruba I'll check this tomorrow, although right now the performance is pretty good and works really nice...
