### ISSUE TITLE
Better Seeding

### ISSUE THREAD

**Issue by jaruba** [jaruba/PowderPlayer#58]
I'm making this request to keep track of possible ideas and solutions for better seeding.

**The issues:**

- <del>It is my understanding that `torrent-stream` seeds perfectly upon finishing the download. Once fully downloaded, it continues to seed to the connected peers. If the torrent is well seeded, it then stops looking for new peers, otherwise, if it has few seeds it will continue to seed upon closing the app.</del> - `fixed`

- As Powder is instance based this is even a greater problem as it could not compete to daemon/service like software (such as uTorrent) that encourage leaving it open all the time in the background to seed.

**Possible solutions:**

- <del>torrent-stream should always seed until the Powder instance is closed unless the users select some option to not do this from the settings.</del> - `done`

- A separate executable could be bundled with Powder or available as a plugin that would be a service/daemon, running at all times on the system. Upon closing Powder, users should be prompted with the option of continuing to seed that torrent or not, if they choose to seed, the torrent should be sent to the seeder that should use a more flexible torrent client library such as `libtorrent` to keep seeding that torrent. The seeder should have an UI where users can manage and remove their torrents. (starting the seeder as a service/daemon should again, be the user's choice)

- <del>Although a bit of topic: a plugin that will allow people to use powder with seedboxes that will obviously resolve the issue of seeding and would keep user's torrent activity anonymous. A seedbox service with a good API should make it possible to interact with the seedbox from Powder's UI.</del> - `invalid`

**Comment by Mel79** [comment]
I don't know if this is still an issue with the current build. But I think the first option of stopping the torrent-stream when Powder instance is closed, unless the user selects an option not do this from the settings menu would be the best, and probably the simplest solution.

**Comment by iadj** [comment]
Actually came here to make a post with the same suggestion. Seeding is super important with the rising popularity of streaming clients, and would help torrents live consistently.
I'd love ability to have Powder Player launch on start-up, and to immediately start seeding all the torrents I previously streamed/downloaded like a regular Torrent client.

**Comment by jaruba** [comment]
I know the importance of this, you've both made good points, I'll try to find the best solution for it as soon as I'll have some time.

**Comment by samukets** [comment]
I love idea about powder have UI to manage torrents and a different UI to player. i really dont like use powder to manage normal torrents like .exe and other files for that a use utorrent because its more clear the interface.

Jaruba, please, add more options to control bandwidth like download speed limit, upload speed limit and ratio upload control...

**Comment by jaruba** [comment]
@Mel79 @iadj

With yesterday's release, there have been amazing improvements to the download speed and seeding, there is now also an option in the settings to make powder stop seeding after it's done downloading, but by default it will seed constantly as long as the window is open.

I've seen it even upload 10gb on a 300mb torrent with a powder window left open overnight.

I like the idea of having a manager for all the torrents too, but I'm wondering if that shouldn't be a different project that just keeps track of powder's torrents and runs a few of them on demand in hidden windows to keep seeding.

**Comment by iadj** [comment]
Awesome, great enhancement!

As for torrent management:
I can imagine the many people who are already familiar with torrents, who I believe are currently the majority of Powder Player's user base (me included), would love to have a familiar interface that allows them to manage multiple files.
Not only is this essentially a **requirement** for private trackers (a lot of trackers require users to seed a torrent at least to a 1:1 upload/download ratio), it also allows for a bridge, so to speak, to be established between both of Powder Player's main user groups: those who are, and those who aren't familiar with torrents.

Experienced users get to transition from established clients (i.e. uTorrent or qBittorrent) to a user-friendly, next generation experience, all the while still having everything they need for their daily familiar torrent usage.
Those who are new to torrents would get a familiar web-like streaming experience, and have the ability to stream, or save any content they want for later usage (essential for users with slower connections or frequent 'mobile content watchers').

No matter what features someone uses, a management interface for long-term seeding and file management will help keep torrents alive and well. It would be a perfect enhancement to Powder Player.

**Comment by jaruba** [comment]
I'm closing this as Powder now seeds pretty well, I see no way to make it seed better. I'll start a different ticket for a Torrent Manager.
