### ISSUE TITLE
External Player: MPV

### ISSUE THREAD

**Issue by simonrosted** [jaruba/PowderPlayer#60]
Hi there,

is it possible to support mpv (mpv.io) as default video player?

Thanks in advance

**Comment by jaruba** [comment]
Well it can't really be "the default video player" as their both players.. :))

But I can make it an option in the external players list if you want:

![external-players](https://cloud.githubusercontent.com/assets/1777923/11180352/bd4465ea-8c62-11e5-9220-acdad1f4dfdf.png)

*As I'm all about that love..*

As your a user of MPV, could you explain why you prefer it over VLC? You don't really need to tell me, but I'm curious as I couldn't find a list of MPV's current features..

**Comment by simonrosted** [comment]
Oh yes, that's exactly what i ment :) Thanks!

In regards to choosing mpv over VLC, i guess it down to previous experience with Mplayer (vs. VLC). That, and it's a pleasure to see how basically one man is so passionate about one project, that i devotes his time to it every single day. You should take a look at their git, it's quite impressive.

**Comment by jaruba** [comment]
I can respect that. I've been working on Powder pretty much every day for the past 9 months. :)

**Comment by jaruba** [comment]
@simonrosted

I'm having some trouble finding the default paths of mpv player on all platforms, for Windows I got an archive with 3 files inside it, people could literally put these files anywhere.

What OS are you on and where is mpv located on your system?

I'm wondering if it wouldn't be better to just make a "Browse for Player" option so people can use Powder with any player they want. What do you think?

**Comment by simonrosted** [comment]
I'm on OSX and an Ubuntu based distro (elementary OS).

It could work with an option to browse for the player. However, I recall that what is now known as Project Butter have a great implementation to choose from all the major players that might be installed on the users computer. (Their Chromecast implementation was awesome as well BTW) :)

**Comment by jaruba** [comment]
Yeah, their scanning all folders in these paths:

```
    // linux
    addPath('/usr/bin');
    addPath('/usr/local/bin');
    // darwin
    addPath('/Applications');
    addPath(process.env.HOME + '/Applications');
    // win32
    addPath(process.env.SystemDrive + '\\Program Files\\');
    addPath(process.env.SystemDrive + '\\Program Files (x86)\\');
    addPath(process.env.LOCALAPPDATA + '\\Apps\\2.0\\');
```

but this does not guarantee it will find your player, as you can install it somewhere else too. As I said, mpv on windows does not have any installer, just an archive. :)

Peerflix on the other hand doesn't look for mpv at all, it just runs `mpv` in the terminal, which is better, but still won't work on windows in this case.

"Browse for Player", although not as user friendly, will not only ensure it finds the player, but it will support any player known to man, not just the 12 players that PCT used to have.

**Comment by vankasteelj** [comment]
Ah, also: https://gist.github.com/vankasteelj/dbf28309b0e18df5f8df

**Comment by jaruba** [comment]
Ok, so:

- added a player scanner (courtesy of @vankasteelj) that checks the usual install folders for these players: `VLC`, `MPlayer`, `MPV`, `MPC-HC`, `MPC-BE`, `SMPlayer`, `Bomi`, `PotPlayer`
- added a "Browse for Player" option
- added a button to set custom command line args for the players too

_Will be available in the next version. (v0.97)_
