### ISSUE TITLE
Downloaded: 0 kB / 751.0 MB - doesn't change

### ISSUE THREAD

**Issue by bryanrasmussen** [jaruba/PowderPlayer#62]
the screen showing how quickly you are downloading seems off, it says Downloaded: 0 kB / 751.0 MB and it has said that for a long time, despite 
1. part of the file has been downloaded. 
2. I have a 7.33 Mbps connection at the moment. 

I'm getting some errors in the terminal 

>> [36504:1117/063014:INFO:CONSOLE(2051)] "Uncaught TypeError: undefined is not a function", source: /Users/bryan/projects/repositories/PowderPlayer/node_modules/pw-wcjs-player/index.js (2051)
>> [36504:1117/063017:ERROR:nw_shell.cc(335)] TypeError: undefined is not a function
>>     at hideUI (/Users/bryan/projects/repositories/PowderPlayer/node_modules/pw-wcjs-player/index.js:2051:44)
>>     at null._onTimeout (/Users/bryan/projects/repositories/PowderPlayer/node_modules/pw-wcjs-player/index.js:1434:85)
>>     at Timer.listOnTimeout (timers.js:90:15)
>> [36504:1117/063017:INFO:CONSOLE(2051)] "Uncaught TypeError: undefined is not a function", source: /Users/bryan/projects/repositories/PowderPlayer/node_modules/pw-wcjs-player/index.js (2051)

I'm on Mac OSX Yosemite.

**Comment by jaruba** [comment]
I'm guessing you built Powder, not downloaded and installed it?

**Comment by bryanrasmussen** [comment]
yeah - is there something in the build process I left out that would be
causing this?



On Tue, Nov 17, 2015 at 11:42 AM, Branza Alexandru <notifications@github.com

**Comment by jaruba** [comment]
Most probably, can you explain the steps you took to build it?

**Comment by bryanrasmussen** [comment]
yeah it's been some days ago but I think just did npm install ( I might
have had to do sudo npm install though) and then I put nwjs into the
PowderPlayer root folder.



On Tue, Nov 17, 2015 at 11:52 AM, Branza Alexandru <notifications@github.com

**Comment by jaruba** [comment]
Do the videos from the torrent ever start playing?

**Comment by bryanrasmussen** [comment]
yes they play.

I have some network issues as well that I have to address with my provider
tomorrow, but I believe the consequence of those is that often my openvpn
goes out, or not everything finishes downloading and the most efficient way
to deal with it is to restart the download.


However, as I said, I believe that part is the network issue. That was
actually what lead me to note something was weird this morning.

I had a torrent in excellent health, left it to download for 20 minutes,
came back and it had downloaded evidently 4 mb and was stuck, but the UI
said 0 was downloaded. restarted got 300 mb, stuck again, UI still said 0
downloaded, so then I went to work. So actually given the bad network right
now I actually want to know even more accurately how things are downloading
:) but yes, the video plays fine until my network issue takes effect.



On Tue, Nov 17, 2015 at 12:08 PM, Branza Alexandru <notifications@github.com

**Comment by jaruba** [comment]
Well, considering that you built it a few days ago, the lines in the `pw-wcjs-player` repo should be the same as the ones you have locally, but the errors that you posted make no sense, and I believe are unrelated to your issue.

For example most of the errors say their on this line:
https://github.com/jaruba/pw-wcjs-player/blob/master/index.js#L2051

and that `hideUI` is not a function, which is silly and hilarious at the same time, as that line is literally inside the `hideUI` function.
The result of this error cannot be not downloading though as it should just not hide the player's UI if it happens. As all the errors are from a different module then the downloader UI it cannot break the JS so they should not be related.

Considering this is a special case that truly makes no sense from all points of view, I would suggest trying to use the latest released version for OSX from the download page:
http://powder.media/download

If it works with that version, then it most probably is a building issue and I should attempt to debug the building process for OSX.

**Comment by bryanrasmussen** [comment]
Ok I'll try that in a  few hours from now and report back how it goes.

On Tue, Nov 17, 2015 at 12:42 PM, Branza Alexandru <notifications@github.com

**Comment by jaruba** [comment]
no answer for a long time, closing this for now, if there are still issues, please reopen the ticket.
