### ISSUE TITLE
Support for WebTorrent

### ISSUE THREAD

**Issue by Chaz6** [jaruba/PowderPlayer#67]
It would be great to be able to use PowderPlayer as a hybrid bittorrent/WebTorrent client.

https://webtorrent.io/faq

**Comment by jaruba** [comment]
I am familiar with webtorrent, but I am unsure of how Powder could add webtorrent support.

You mean you'd like Powder to share it's peers with webtorrent so webtorrent can grow it's peer base? If so.. then peerflix and webtorrent should share their peers. If they would, then this change would be made in Powder too..

Otherwise, I see no interest or advantage to adding webtorrent support as it won't do anything more or better then peerflix for this app.

**Comment by Chaz6** [comment]
The more peers you can connect to the better; although webtorrent is small, the fact that it is easy to embed in web pages means that the potential pool is massive, so I think it will be highly beneficial to PowderPlayer users.

**Comment by Ivshti** [comment]
@jaruba it's not actually that hard to integrate webtorrent, mafintosh and feross have made some changes that allowed torrent-stream and webtorrent to be to some level, compatible. You should check mafintosh/playback - he has replaced torrent-stream with webtorrent with almost a drop-in change.

**Comment by jaruba** [comment]
How do you guys imagine this being done? As a setting to select Peerflix or WebTorrent? Or use both at the same time? (is that even possible?)

**Comment by Chaz6** [comment]
Unfortunately I don't understand the nuts and bolts; as an end user, I see it that PowderPlayer should be able to use both regular bittorrent and webtorrent peers when streaming.

**Comment by jaruba** [comment]
I've been looking into this, and my first presumption seems to be correct, it looks like feross and mafintosh have already talked this out and `torrent-stream` is already moving twords unification with `webtorrent`, might even be done already.

So Powder will support and share peers with `webtorrent` naturally by the looks of it. It will just take some time, but requires no effort from my side.

**Comment by jaruba** [comment]
Looked even more into it, it seems that with this commit on `torrent-stream`:
https://github.com/mafintosh/torrent-stream/commit/072bcb6a2cbd604111293293b7dfcc4d888e9023

Peer discovery has been moved to [torrent-discovery](https://github.com/feross/torrent-discovery), description writes:

> Discover BitTorrent and WebTorrent peers

So yes, I'm now fully sure that the next `peerflix` update will support webtorrent peers too.
