### ISSUE TITLE
[DLNA] Subtitles are not served

### ISSUE THREAD

**Issue by bsphere** [jaruba/PowderPlayer#70]
when streaming to DLNA/UPNP (Kodi receiver), the subtitles which are visible before streaming are not server (Kodi doesn't get the subtitles). also, the stream name is not meaningful so for downloading the subtitles from Kodi a manual search is needed..

**Comment by jaruba** [comment]
Yes, your right, dlna subtitles have not been implemented yet. I'm glad to hear it works to cast to kodi though.

**Comment by bsphere** [comment]
are you planning to implement that any time soon? is it possible to have the file/torrent name as the dlna stream name (instead of 0) for now so subtitles can be downloaded automatically by Kodi ?

**Comment by jaruba** [comment]
From the other implementations I've seen around, it should be possible to customize the stream names too.

As for how soon we can do this, currently we're stuck in fixing some performance issues with the react version in which we're rewriting everything. If it will take longer then I expect I'll probably do another release with more dlna work, chromecast and airplay.

**Comment by vankasteelj** [comment]
https://github.com/jaruba/PowderPlayer/tree/vkj/dlna_subs

working on LG/Philips. For Samsung, don't use my upnp-mediarenderer fork.

Needs a complete rewrite, it's just "working".

**Comment by jaruba** [comment]
> don't use my upnp-mediarenderer fork

![q3icwqe](https://cloud.githubusercontent.com/assets/1777923/13585415/7786b4c6-e4c4-11e5-9515-7e5c26f819b6.gif)

**Comment by vankasteelj** [comment]
PROOF FOR THE NON BELIEVERS! 

![img_20160307_230157328](https://cloud.githubusercontent.com/assets/12599850/13585857/5e2aa7fe-e4be-11e5-972c-f7859076337b.jpg)

**Comment by jaruba** [comment]
@vankasteelj 
![amazing](https://cloud.githubusercontent.com/assets/1777923/13585964/1c595376-e4c7-11e5-957e-d5054d1e9030.gif)

**Comment by vankasteelj** [comment]
github is severely lacking a "like" button :+1:

**Comment by jaruba** [comment]
It is now possible to cast to DLNA, Chromecast, Airplay, the Browser, other Players, Friends, etc. with subtitles (but only with Transcode set to "Yes") in Powder Player Nightly. You can also set subtitle size, color and position.

I will also attempt to make subtitles work without transcoding in the future, but this is all I got for now..

The official announcement for Powder Player Nightly Pre-Release and the download link can be found here:
https://www.reddit.com/r/PowderPlayer/comments/4ralk2/powder_player_v100_prerelease_available_for/
