### ISSUE TITLE
Remove animations from app

### ISSUE THREAD

**Issue by PaulAnnekov** [jaruba/PowderPlayer#71]
Slow animations in app is bad UX decision. I don't want to wait while it will animate some modal box. I just want to enter magnet url and play my video as fast as it can. 
It's not a web application, it's desktop app. But even for web these animations are very slow and annoying.
Please, remove all these animations. Just show the modal box.

**Comment by vankasteelj** [comment]
I fancy animations. Please make it a setting, live the android developper settings allow on Android :p

**Comment by jaruba** [comment]
@PaulAnnekov

Fastest way to start streaming is to associate with magnet links, in which case you'll skip the modals all together. Another way to skip the modals is to drag and drop magnet links in powder.

The animations do not delay the streaming at all though.. I'll think about how to make a setting for it though..

**Comment by jaruba** [comment]
@luigiplr:

![16794f1285f65b0ad2b5d216688b747d](https://cloud.githubusercontent.com/assets/1777923/12625016/8be07154-c53a-11e5-8459-ff841675e1a5.gif)

**Comment by PaulAnnekov** [comment]
@jaruba it's not only streaming. I hate to wait this animation while waiting for my `Settings` modal box. I don't remember any desktop app that makes user wait while doing nothing (animation == nothing).

**Comment by jaruba** [comment]
@PaulAnnekov Well.. that modal animation was always too slow, I agree that it would be better to not have an animation at all for modals.. The initial animation when loading the app should stay though, it's just a loading animation..

**Comment by jaruba** [comment]
Done, in the next update the modals will no longer be animated.
