### ISSUE TITLE
Load Subtitle From Torrent

### ISSUE THREAD

**Issue by jaruba** [jaruba/PowderPlayer#72]
[requested by email]

There should be a setting that enables loading the subtitles available inside the torrents. (if there is only 1 subtitle file)

**Comment by vankasteelj** [comment]
I haz code for that, well, not for Powder, but meh, could be used as base:

https://github.com/vankasteelj/opensubtitles-uploader/commit/0084bc27d48a3bfd1cc7c7175f5dd4319f2e703d

**Comment by jaruba** [comment]
the problem I see with this is that we need to make sure `torrent-stream` downloads subtitles before media files

**Comment by jaruba** [comment]
I have a feeling we can hack it though.. If we just connect to the stream of the subtitle file before playing any media file, `torrent-stream` should prioritize it's download before anything else.

**Comment by samukets** [comment]
If this enhancement has implemented, how about playlists with has more them one video and one subtitle?

**Comment by jaruba** [comment]
Playlists should be supported, ofcourse. :)

**Comment by jaruba** [comment]
done
