### ISSUE TITLE
deprecated bittorrent-dht@3.2.6

### ISSUE THREAD

**Issue by pguth** [jaruba/PowderPlayer#74]
```sh
npm WARN deprecated bittorrent-dht@3.2.6:
Critical security issue fixed in 5.1.3. All users should upgrade.
(More info: https://github.com/feross/bittorrent-dht/issues/87)
```

> We just fixed a security issue in the bittorrent-dht module that would allow an attacker to send a specific series of messages to a listening peer to make it disclose internal memory of the node.js process.
> 
> All users of bittorrent-dht should upgrade to version 5.1.3 or later.

**Comment by jaruba** [comment]
i bumped bittorrent-dht to 6.4.0 (latest)

**Comment by cristian100** [comment]
how?

**Comment by jaruba** [comment]
@cristian100 how what? :))
