### ISSUE TITLE
Manual set Subtitle color and size Videostream reference

### ISSUE THREAD

**Issue by samukets** [jaruba/PowderPlayer#76]
it will very good if in the next versions the subtitle font, color and size can be programmed manually on menu like yellow, size 32 font X. Think about, maybe on v 1.0

**Comment by samukets** [comment]
![image](https://cloud.githubusercontent.com/assets/2901904/12906316/cc77cb2c-cebd-11e5-93aa-acb2341f2085.png)

this is a menu of video stream from subtitle, is very easy and complete, good to be a reference to powder v1

**Comment by samukets** [comment]
but i guess when preferred language was not found the powder have to be a option to auto select unknown subtitle or trilha 1 subtitle... in videostream we only have one preferred language but in powder it will be great if we have option to set in preference order the languages like:

1- Portuguese (Brazil) if not found use the second choice unknown subtitle (internal subtitle like use this name) if not found use the third choice "trilha 1"...

**Comment by samukets** [comment]
other good think is use regional sites, subtitle sites like in kodi (Pulsar) to search subtitle, example in brazil, legendas.tv, pipocas.tv... if kodi has this why powder dont?

**Comment by jaruba** [comment]
Powder v1.0 already has some subtitle settings:

![c33ae6f8-b2ec-11e5-9134-f1d69da0b94f](https://cloud.githubusercontent.com/assets/1777923/12906737/ec657f82-ceeb-11e5-98e2-a19b05c9fda6.png)

I've added some subtitle settings to the next update too:

![subs-now](https://cloud.githubusercontent.com/assets/1777923/12906766/32f6d1da-ceec-11e5-9af8-4420b13c0fde.png)

Also note that there are hotkeys for subtitle settings also:

https://github.com/jaruba/PowderPlayer/wiki/Hotkeys#subtitles

(that also allow positioning them)

I like the position selector from your example though, I was wondering how to do that best..

**Comment by samukets** [comment]
Some way to set default audio track language too?

**Comment by jaruba** [comment]
You can change the audio track from the context menu (right click, "Audio Tracks" category), but I don't think that a default can ever be set to automatically change when playback starts.. most subtitle tracks have names like "Track 1", "Track 2", etc. So we can't determine the language from it.

**Comment by jaruba** [comment]
I've made a new ticket for this: https://github.com/jaruba/PowderPlayer/issues/77

As only Default Subtitle Position is missing, Powder doesn't need a setting for default subtitle language because it always remembers your last language choice and auto-selects it.
