### ISSUE TITLE
subtitles drag and droped from zip (rar, etc) files dont work

### ISSUE THREAD

**Issue by samukets** [jaruba/PowderPlayer#79]
(Question) 1- when i do a subtitle download, open zip file and drag and drop to powder, the player recognize the subtitle but do not show on movie i need to extract subtitle to PC and so drag an drop to powder to show subtitle, this is a bug?

(Suggestion) 2- It would be great to drag and drop a zip or rar file with the subtitle inside and powder load all subtitles inside zip file .

**Comment by jaruba** [comment]
I added support to drag and drop `.zip` and `.gz` archives with subtitles.. I did not add `.rar`, personally, I haven't seen rar archives with subtitles yet. Was the file you tried to use it with `.zip` or `.rar`?

**Comment by samukets** [comment]
.zip, thx for the enhancement, you know, you are the guy!

**Comment by jaruba** [comment]
Ok, then I'll consider this ticket closed, if someone needs this for rar archives they should make a new ticket. Although I don't think that will be needed..
