### ISSUE TITLE
Setting to Change Single / Multi Process

### ISSUE THREAD

**Issue by jaruba** [jaruba/PowderPlayer#81]
[requested by chat]

There should be a setting to change if the app should work in multiple processes (default) or a single process. (by just adding to it's playlist)

**Comment by luigiplr** [comment]
>[requested by chat]

![](http://cdn.meme.am/instances/500x/59083117.jpg)

**Comment by jaruba** [comment]
This setting does not use the native Single Process feature of NW.js.

So a better way of doing it is by leaving the `Process Type` setting to `Multiple` and setting this line:

```
    "single-instance": true,
```

in `package.json` from the install path.

Since I can't be sure if I'll have access to modify this file on the user's PC, the way this new setting does is the next best thing.
