### ISSUE TITLE
Setting for Internal Video Subtitles

### ISSUE THREAD

**Issue by samukets** [jaruba/PowderPlayer#84]
Thats is a good option to implement, when Powder dont find any subtitle and we have only one, internal subtitle ou external, Powder automatic load that... If audio e subtitle do not use same language...

**Comment by samukets** [comment]
![image](https://cloud.githubusercontent.com/assets/2901904/13351456/875d5394-dc65-11e5-9bc0-099ec820593b.png)

When no subtitle found, auto open subtitle it only one exist...

![image](https://cloud.githubusercontent.com/assets/2901904/13351492/ae0c7484-dc65-11e5-9312-f43e568656f1.png)

**Comment by samukets** [comment]
https://drive.google.com/file/d/0B-zID4I33vBSbTF4V1BJSUUwQjQ/view?usp=sharing

Example of files

**Comment by jaruba** [comment]
I'm not even sure how to call this setting, but I do know it shouldn't be turned on by default..

**Comment by samukets** [comment]
Auto Load one subtitle if only one available. uahuah

**Comment by jaruba** [comment]
There are now 2 features that can set the subtitle automatically.

First priority is the "Load from Torrent" setting, so if it finds a subtitle in the torrent with the same name as the video, it loads it.

Second priority is the OpenSubtitles feature, if it finds your last selected subtitle, it loads it, but only if the "Load from Torrent" setting previously failed.

So what is the priority that this should have? Should it only load it if a torrent subtitle was not found? Should it wait for the OpenSubtitles feature to finish searching too?

**Comment by samukets** [comment]
In this case i guess first priority.

Look that scenario:

You stream a torrent, first power will search from inside subtitles in video (is a best trustworthy fount), if exist powder load if not powder goes to find subtitle from torrent file (is the best second fount) and if not that happens powder search from opensub witch has too many broken or bad subs...

**Comment by samukets** [comment]
Sorry dude for inconvenience but .srt from torrent is the best choice ever, after internal and for the last opensub... Really sorry

**Comment by samukets** [comment]
My fault, if you can re-open the case to further adjusts
