### ISSUE TITLE
Youtube Playlist issues

### ISSUE THREAD

**Issue by samukets** [jaruba/PowderPlayer#85]
Please, try to open this youtube playslist (https://www.youtube.com/playlist?list=PLDcnymzs18LVXfO_x0Ei0R24qDbVtyy66) Powder dont works well with big playlist. Dont playback well and stay too much time on loading resources...

**Comment by samukets** [comment]
See playlist vídeo names, dont works well too

**Comment by samukets** [comment]
![image](https://cloud.githubusercontent.com/assets/2901904/13351389/231e91ae-dc65-11e5-8932-1fb5d9101936.png)

**Comment by jaruba** [comment]
I think the titles broke with the deprecation of Youtube API v2, but I know how to fix those.

The videos that don't play are most probably ]set to not be embeddable on other pages by their authors, I'll see what I can do though.

**Comment by jaruba** [comment]
fully fixed
