### ISSUE TITLE
Auto load subtitle from torrent dont work on playlist

### ISSUE THREAD

**Issue by samukets** [jaruba/PowderPlayer#87]
Auto load subtitle from torrent works good if we have one media file and a subtitle, but when choose a season of series dont work...

**Comment by samukets** [comment]
Maybe option to first download subtitles...

**Comment by jaruba** [comment]
it already has such an option, that i thought worked..

can you mail me a way to reproduce your playlist scenario?

**Comment by samukets** [comment]
Private message on gitter chat...

**Comment by samukets** [comment]
Sorry, send to email...  thx

**Comment by samukets** [comment]
Email sent...

**Comment by jaruba** [comment]
it works, don't worry :)
