### ISSUE TITLE
Windows size cut final text

### ISSUE THREAD

**Issue by samukets** [jaruba/PowderPlayer#90]
Windows size cut final text

![image](https://cloud.githubusercontent.com/assets/2901904/13556299/0fb349c8-e3b5-11e5-9700-632a411f03e5.png)

**Comment by jaruba** [comment]
This is because the big text (Drag & Drop a File) is expected to be on one line, the text being significantly longer needs to be shown on 2 lines, pushing everything else after it down too.

**Comment by samukets** [comment]
Lets resolve that:

Change "Arraste e Solte Um arquivo Nesta Janela" to "Arraste e Solte Um arquivo"

**Comment by jaruba** [comment]
![snuggly](https://cloud.githubusercontent.com/assets/1777923/13558095/221cd2ba-e404-11e5-8d77-2c38b56cbb31.png)

**Comment by luigiplr** [comment]
>snuggly.png

![](http://replygif.net/thumbnail/382.gif)

**Comment by samukets** [comment]
PERFECT!

**Comment by jaruba** [comment]
@luigiplr 
![tumblr_n0e2qlyx7h1s0jfv8o3_400](https://cloud.githubusercontent.com/assets/1777923/13559764/42ad34e0-e420-11e5-97e7-663c967e1e1f.gif)
