### ISSUE TITLE
[Setting] Subtitle Encoding doesn't work correctly

### ISSUE THREAD

**Issue by samukets** [jaruba/PowderPlayer#95]
On previous versions i always have to set windows 1252 to see correct characters, now on 0,98 windows 1252 dont work and i need set to auto to see correct...

**Comment by jaruba** [comment]
don't forget to send me an email with something that i can test this on.

**Comment by samukets** [comment]
lol, uhau, :) sent on chat...

**Comment by jaruba** [comment]
this is about version 0.98 which is now deprecated, the new version has been re-written from scratch so this does not apply anymore
