### ISSUE TITLE
[Feature] Torrent Manager

### ISSUE THREAD

**Issue by jaruba** [jaruba/PowderPlayer#96]
Largely based on the discussion from: https://github.com/jaruba/PowderPlayer/issues/58

Although Powder now seeds pretty well and I've personally seen it in more then once upload 9gb while watching a 40 minute video that has only 350mb, there is still something that's missing.

**Issue:**

As Powder is instance based it cannot compete to daemon/service like software (such as uTorrent) that encourage leaving it open all the time in the background to seed.

**Possible Solution:**

A separate executable could be bundled with Powder or available as a different app that would be a service/daemon, running at all times on the system.

Upon closing Powder, users should be prompted with the option of continuing to seed that torrent or not, if they choose to seed, the torrent should be sent to the torrent manager.

**Comment by samukets** [comment]
Good feature, following...

**Comment by omgbox** [comment]
interesting must be a dedicated daemon, a separate process outside powder,  which only seeds through normal torrent protocols and web seed http :+1:

**Comment by jaruba** [comment]
No longer relevant, I've made a separate project for this purpose: [Powder Web](https://github.com/jaruba/PowderWeb)
